#Creator: Sandrix33
#Twitch channel: https://www.twitch.tv/sandrix33
#Config version: 0.2
#Permission: 
#User: "xpp.use"
#Admin: "xpp.admin"

#[ITA]-Abilita la possibilità di guadagnare xp scavando blocchi
#[ENG]-Enable the ability to earn xp by digging blocks

Earnxp: true 

#[ITA]-Messaggio di permesso mancante
#[ENG]-Missing permission message

permissionMessage: "&cYou are not allowed"

#[ITA]-Imposta se lo strumento da utilizzare deve contenere una descrizione specifica
#[ENG]-Sets whether the tool to be used should contain a specific description

itemWithSpecificLore: true 

#[ITA]-Descrizione che deve avere l'item per ricevere xp
#[ENG]-Description that the item must have to receive xp

itemLore: "&7XP Recovery" 

#[ITA]-Lista dei blocchi che fanno guadagnare xp, quantità di esperienza guadagnata, numero di blocchi da rompere prima di ricevere l'esperienza, il contatore dei blocchi di ogni giocatore si resetta ad ogni reload
#[ENG]-List of blocks that earn xp,amount of experience gained, number of blocks to break before receiving the experience, each player's block counter resets with each reload
#[Format] - {Material Block}, {value}, {block count}

Blocks:
  - CYAN_TERRACOTTA, 100, 1
  - STONE, 20, 2

#[ITA]-Abilita la possibilità di moltiplicare il guadagno di xp tramite permessi
#[ITA]-Se si dispone di più permessi il plugin sommerà i moltiplicatori
#[ENG]-Enable the ability to multiply the gain of xp through permissions
#[ENG]-If you have multiple permissions the plugin will add up the multipliers
#[Format] - {permission}, {value}

multipliers: true 

#[ITA]-Lista moltiplicatori
#[ENG]-Multiplier list

list:
  - xp.multipliers.2, 2.0
  - xp.multipliers.3, 3.0